# Generated by Django 5.1.6 on 2025-03-04 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('supplier', models.CharField(max_length=200)),
                ('current_stock', models.IntegerField(default=0)),
                ('minimum_stock', models.IntegerField(default=5)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('registration', models.CharField(max_length=20, unique=True)),
                ('vin', models.CharField(max_length=50, unique=True, verbose_name='VIN')),
                ('current_mileage', models.IntegerField()),
                ('purchase_date', models.DateField()),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('last_service_mileage', models.IntegerField(blank=True, null=True)),
                ('service_interval_months', models.IntegerField(default=6)),
                ('service_interval_miles', models.IntegerField(default=10000)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('mileage_at_service', models.IntegerField()),
                ('service_type', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('performed_by', models.CharField(max_length=200)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='vehicle_management.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePartUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='vehicle_management.servicerecord')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_management.vehiclepart')),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePartCompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatible_vehicles', to='vehicle_management.vehiclepart')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatible_parts', to='vehicle_management.vehicle')),
            ],
            options={
                'verbose_name_plural': 'Vehicle Part Compatibilities',
                'unique_together': {('vehicle', 'part')},
            },
        ),
    ]
