# Generated by Django 5.1.7 on 2025-03-06 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0004_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to='vehicle_management.employee'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='employee_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='insurance_company',
            field=models.CharField(blank=True, max_length=100, verbose_name='Insurance'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Insurance Expiry'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Vehicle ID'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration',
            field=models.CharField(max_length=20, unique=True, verbose_name='Registration'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Reg Expiry'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('maintenance', 'In Maintenance'), ('off_road', 'Off Road'), ('decommissioned', 'Decommissioned')], default='active', max_length=20, verbose_name='Status'),
        ),
    ]
